import type { SportKey } from "../constants.js";

/**
 * Player-level Over/Under prop catalog per sport - human-readable label to statID,
 * extracted directly from SportsGameOdds' published market CSVs (full-event,
 * player-level Over/Under rows only). Used by tkb_get_odds to construct exact
 * oddIDs instead of loose text matching.
 */
export const OU_PROP_MARKETS: Record<SportKey, { statID: string; label: string }[]> = {
  mlb: [
    { statID: "batting_doubles", label: "Doubles" },
    { statID: "pitching_earnedRuns", label: "Earned Runs" },
    { statID: "fantasyScore", label: "Fantasy Score" },
    { statID: "batting_hits", label: "Hits" },
    { statID: "batting_hits+runs+rbi", label: "Hits + Runs + RBIs" },
    { statID: "pitching_hits", label: "Hits Allowed" },
    { statID: "batting_homeRuns", label: "Home Runs" },
    { statID: "pitching_outs", label: "Outs" },
    { statID: "pitching_pitchesThrown", label: "Pitches Thrown" },
    { statID: "batting_runs+rbi", label: "Runs + RBIs" },
    { statID: "batting_RBI", label: "Runs Batted In" },
    { statID: "points", label: "Score" },
    { statID: "batting_singles", label: "Singles" },
    { statID: "batting_stolenBases", label: "Stolen Bases" },
    { statID: "batting_strikeouts", label: "Strikeouts (batter)" },
    { statID: "pitching_strikeouts", label: "Strikeouts (pitcher)" },
    { statID: "batting_totalBases", label: "Total Bases" },
    { statID: "batting_triples", label: "Triples" },
    { statID: "pitching_basesOnBalls", label: "Walks (pitcher)" },
    { statID: "batting_basesOnBalls", label: "Walks (batter)" },
  ],
  wnba: [
    { statID: "assists", label: "Assists" },
    { statID: "blocks", label: "Blocks" },
    { statID: "blocks+steals", label: "Blocks + Steals" },
    { statID: "fantasyScore", label: "Fantasy Score" },
    { statID: "fieldGoalsMade", label: "Field Goals Made" },
    { statID: "freeThrowsAttempted", label: "Free Throws Attempted" },
    { statID: "freeThrowsMade", label: "Free Throws Made" },
    { statID: "points+assists", label: "Points + Assists" },
    { statID: "points+rebounds", label: "Points + Rebounds" },
    { statID: "points+rebounds+assists", label: "Points + Rebounds + Assists" },
    { statID: "rebounds", label: "Rebounds" },
    { statID: "rebounds+assists", label: "Rebounds + Assists" },
    { statID: "points", label: "Score" },
    { statID: "steals", label: "Steals" },
    { statID: "threePointersMade", label: "Three Pointers Made" },
    { statID: "turnovers", label: "Turnovers" },
  ],
  nfl: [
    { statID: "defense_assistedTackles", label: "Assisted Tackles" },
    { statID: "defense_combinedTackles", label: "Combined Tackles + Assists" },
    { statID: "extraPoints_kicksMade", label: "Extra Points Made" },
    { statID: "fantasyScore", label: "Fantasy Score" },
    { statID: "fieldGoals_made", label: "Field Goals Made" },
    { statID: "defense_interceptions", label: "Interceptions" },
    { statID: "kicking_totalPoints", label: "Kicking Total Points" },
    { statID: "passing_longestCompletion", label: "Longest Completion" },
    { statID: "receiving_longestReception", label: "Longest Reception" },
    { statID: "rushing_longestRush", label: "Longest Rush" },
    { statID: "passing+rushing_yards", label: "Passing + Rushing Yards" },
    { statID: "passing_attempts", label: "Passing Attempts" },
    { statID: "passing_completions", label: "Passing Completions" },
    { statID: "passing_touchdowns", label: "Passing Touchdowns" },
    { statID: "passing_yards", label: "Passing Yards" },
    { statID: "receiving_touchdowns", label: "Receiving Touchdowns" },
    { statID: "receiving_yards", label: "Receiving Yards" },
    { statID: "receiving_receptions", label: "Receptions" },
    { statID: "rushing+receiving_yards", label: "Rushing + Receiving Yards" },
    { statID: "rushing_attempts", label: "Rushing Attempts" },
    { statID: "rushing_touchdowns", label: "Rushing Touchdowns" },
    { statID: "rushing_yards", label: "Rushing Yards" },
    { statID: "defense_sacks", label: "Sacks" },
    { statID: "points", label: "Score" },
    { statID: "defense_soloTackles", label: "Solo Tackles" },
    { statID: "touchdowns", label: "Touchdowns" },
    { statID: "turnovers", label: "Turnovers" },
  ],
  cfb: [
    { statID: "extraPoints_kicksMade", label: "Extra Points Made" },
    { statID: "fantasyScore", label: "Fantasy Score" },
    { statID: "fieldGoals_made", label: "Field Goals Made" },
    { statID: "defense_interceptions", label: "Interceptions" },
    { statID: "kicking_totalPoints", label: "Kicking Total Points" },
    { statID: "passing_longestCompletion", label: "Longest Completion" },
    { statID: "receiving_longestReception", label: "Longest Reception" },
    { statID: "rushing_longestRush", label: "Longest Rush" },
    { statID: "passing+rushing_yards", label: "Passing + Rushing Yards" },
    { statID: "passing_attempts", label: "Passing Attempts" },
    { statID: "passing_completions", label: "Passing Completions" },
    { statID: "passing_touchdowns", label: "Passing Touchdowns" },
    { statID: "passing_yards", label: "Passing Yards" },
    { statID: "receiving_touchdowns", label: "Receiving Touchdowns" },
    { statID: "receiving_yards", label: "Receiving Yards" },
    { statID: "receiving_receptions", label: "Receptions" },
    { statID: "rushing+receiving_yards", label: "Rushing + Receiving Yards" },
    { statID: "rushing_attempts", label: "Rushing Attempts" },
    { statID: "rushing_touchdowns", label: "Rushing Touchdowns" },
    { statID: "rushing_yards", label: "Rushing Yards" },
    { statID: "defense_sacks", label: "Sacks" },
    { statID: "points", label: "Score" },
    { statID: "touchdowns", label: "Touchdowns" },
  ],
};

/**
 * Yes/No prop catalog per sport - statID and human-readable name, extracted
 * directly from SportsGameOdds' published market CSVs (not guessed). These are
 * "milestone"-style bets: did the player/team do X at all, not an over/under line.
 *
 * cfb here also covers ncaaf naming from the source data.
 */
export const YES_NO_MARKETS: Record<SportKey, { statID: string; label: string }[]> = {
  mlb: [
    { statID: "batting_doubles", label: "Any Doubles" },
    { statID: "pitching_earnedRuns", label: "Any Earned Runs" },
    { statID: "batting_firstHomeRun", label: "First Home Run" },
    { statID: "batting_hits", label: "Any Hits" },
    { statID: "batting_hits+runs+rbi", label: "Any Hits + Runs + RBIs" },
    { statID: "pitching_hits", label: "Any Hits Allowed" },
    { statID: "batting_homeRuns", label: "Any Home Runs" },
    { statID: "pitching_outs", label: "Any Outs" },
    { statID: "pitching_win", label: "Pitching Win" },
    { statID: "batting_runs+rbi", label: "Any Runs + RBIs" },
    { statID: "batting_RBI", label: "Any RBIs" },
    { statID: "points", label: "Any Score" },
    { statID: "batting_singles", label: "Any Singles" },
    { statID: "batting_stolenBases", label: "Any Stolen Bases" },
    { statID: "batting_strikeouts", label: "Any Strikeouts (batter)" },
    { statID: "pitching_strikeouts", label: "Any Strikeouts (pitcher)" },
    { statID: "batting_totalBases", label: "Any Total Bases" },
    { statID: "batting_triples", label: "Any Triples" },
    { statID: "batting_basesOnBalls", label: "Any Walks (batter)" },
    { statID: "pitching_basesOnBalls", label: "Any Walks (pitcher)" },
  ],
  wnba: [
    { statID: "assists", label: "Any Assists" },
    { statID: "blocks", label: "Any Blocks" },
    { statID: "blocks+steals", label: "Any Blocks + Steals" },
    { statID: "doubleDouble", label: "Double-Double" },
    { statID: "firstBasket", label: "First Basket" },
    { statID: "freeThrowsMade", label: "Any Free Throws Made" },
    { statID: "points+rebounds+assists", label: "Any Points + Rebounds + Assists" },
    { statID: "rebounds", label: "Any Rebounds" },
    { statID: "rebounds+assists", label: "Any Rebounds + Assists" },
    { statID: "points", label: "Any Score" },
    { statID: "steals", label: "Any Steals" },
    { statID: "threePointersMade", label: "Any Threes Made" },
    { statID: "tripleDouble", label: "Triple-Double" },
    { statID: "turnovers", label: "Any Turnovers" },
  ],
  nfl: [
    { statID: "defense_safeties", label: "Defensive Safety" },
    { statID: "firstTouchdown", label: "First Touchdown" },
    { statID: "passing_interceptions", label: "Any Interception Thrown" },
    { statID: "lastTouchdown", label: "Last Touchdown" },
    { statID: "passing_touchdowns", label: "Any Passing TD" },
    { statID: "rushing_yards", label: "Any Rushing Yards" },
    { statID: "points", label: "Any Score" },
    { statID: "touchdowns", label: "Any Touchdown" },
  ],
  cfb: [
    { statID: "firstTouchdown", label: "First Touchdown" },
    { statID: "lastTouchdown", label: "Last Touchdown" },
    { statID: "points", label: "Any Score" },
    { statID: "touchdowns", label: "Any Touchdown" },
  ],
};

/**
 * Valid periods per sport (beyond full game), matching real market coverage
 * confirmed from SGO's CSVs. NBA carries the same set as WNBA/NFL/CFB (quarters
 * only, no innings). This is used to validate tkb_get_period_odds input so we
 * fail fast with a clear message rather than silently returning empty results
 * for a period that sport doesn't support.
 */
export const SUPPORTED_PERIODS: Record<SportKey, string[]> = {
  mlb: [
    "1st_half",
    "1st_inning",
    "2nd_inning",
    "3rd_inning",
    "4th_inning",
    "5th_inning",
    "6th_inning",
    "7th_inning",
    "8th_inning",
    "9th_inning",
    "1st_3_innings",
    "1st_5_innings",
    "1st_7_innings",
  ],
  wnba: ["1st_half", "2nd_half", "1st_quarter", "2nd_quarter", "3rd_quarter", "4th_quarter"],
  nfl: ["1st_half", "2nd_half", "1st_quarter", "2nd_quarter", "3rd_quarter", "4th_quarter"],
  cfb: ["1st_half", "2nd_half", "1st_quarter", "2nd_quarter", "3rd_quarter", "4th_quarter"],
};
